Improve sub-context passing ergonomics
ggez/ggez pull request #1037
Opened 2022-05-27 22:45 UTC by nobbele

this allows passing just `ctx` to functions that take sub-contexts.
You can still split borrow with a slightly uglier construction: `&(&ctx.fs, &ctx.gfx)`.
I think something like 99.9% of users won't ever have to split borrow so in my opinion, this is a good trade-off.

2022-05-29 14:23 UTC, PSteinhaus commented
Interesting idea! It certainly improves ergonomics.
Two minor things:
1. Why did you call the context parameter in the `HasTwo` cases `extra`? Wouldn't something like `contexts` be more meaningful?
2. Do you think we should document how to split-borrow the context in some kind of example? I think you're right and most people won't ever use it, but I can imagine that there'll be enough people who _wonder_ why this is the way it is and how the intended use it. I think the best way would be to shortly summarize the idea behind it in the documentation of `Has` and `HasTwo`, including a short code example on how to operate when splitting the context.

It certainly is a bit ugly, but for a library of our size and ambition (i.e. making life as easy as possible) it makes sense to me.

2022-05-29 20:48 UTC, nobbele commented
> Why did you call the context parameter in the HasTwo cases extra? Wouldn't something like contexts be more meaningful?

fair, or `ctxs` or just `ctx`

> Do you think we should document how to split-borrow the context in some kind of example?

sure, I'll write some documentation tomorrow

2022-05-31 12:22 UTC, PSteinhaus requested changes
Almost finished. I found some final places where the `Has`-pattern hadn't yet been adopted and also changed some tiny other things, see the [PR](https://github.com/nobbele/ggez/pull/1).

2022-05-31 21:23 UTC, PSteinhaus approved these changes

2022-05-31 21:27 UTC, merged