Touch event
ggez/ggez pull request #995
Opened 2021-11-21 18:19 UTC by ssciarini

I needed access to the touch event for a project I am doing with a raspberry pi. Rather than writing a custom event loop, this PR will give developers access to the touch events in the same way that we can with mouse & keyboard events.

2021-11-21 18:53 UTC, PSteinhaus commented
I really like this PR. Adding a touch event is definitely a good idea.

Yet, I assume most of our users won't really use it much, as ggez currently doesn't have any mobile support. Still, some laptops do feature touchscreens so it still makes sense to have this. It will also become much more necessary once/if we take the step towards mobile support one day.

But for now I assume most users just want touch events to be handled like the mouse events they probably designed their application around. Due to this it would be nice to change the default implementation of `touch_event` to simulate mouse input, [like in good-web-game](https://github.com/ggez/good-web-game/blob/3ae0d23cd84b921647f1984643b71dab5cfc9f62/src/event.rs#L49-L77), I think.

For ggez the code we'd need to replicate should be [this](https://github.com/ggez/ggez/blob/50918f133785e1ee585c022d94a0176ea0e73887/src/event.rs#L352-L382).

2021-11-21 19:14 UTC, ssciarini commented
I can absolutely look in to making the touchscreen events emulate the mouse functionality!

2021-11-21 22:19 UTC, PSteinhaus commented
Thank you :)

It's not a strict necessity though. I plan on merging your PR anyway.
But if you could add that extra bit of functionality it would of course be very welcome ;)

2021-11-21 22:28 UTC, PSteinhaus requested changes

2021-11-21 22:28 UTC, PSteinhaus commented on src/event.rs
> +                }
You were a bit unlucky with your timing though, as we just merged a PR extending error handling to all methods of `EventHandler`.

To make the new touch event fit that scheme you'd have to adapt this code like this:
```suggestion
                WindowEvent::Touch(touch) => {
                    let res = state.touch_event(ctx, touch.phase, touch.location.x, touch.location.y);
                    if catch_error(ctx, res, state, control_flow, ErrorOrigin::TouchEvent) {
                        return;
                    };
                }
```

Of course, you'd also have to add `TouchEvent` to the `ErrorOrigin` enum.

2021-11-21 22:28 UTC, PSteinhaus commented on src/event.rs
> +    fn touch_event(&mut self, _ctx: &mut Context, _phase: TouchPhase, _x: f64, _y: f64) {}
Also, this method should now return a `GameResult` as well:
```suggestion
    fn touch_event(&mut self, _ctx: &mut Context, _phase: TouchPhase, _x: f64, _y: f64) -> GameResult {
        Ok(())
    }
```

2021-11-21 23:28 UTC, ssciarini commented
Updated this with your suggestions.

I'll start a new branch with mouse emulation enabled after I do a bit more testing here and after updating the new code with the error handling changes. What are your thoughts on keeping the touch_event function in place? In theory it shouldn't be needed if the preference is having it trigger mouse events, but since it is getting merged, I wouldn't want to do something that would break functionality.

Thanks!

2021-11-22 10:57 UTC, PSteinhaus approved these changes

2021-11-22 12:59 UTC, nobbele commented
Seems nice

2021-11-22 12:59 UTC, merged